version: 2.1

orbs:
  node: circleci/node@5.2.0

executors:
  playwright:
    docker:
       - image: mcr.microsoft.com/playwright:v1.43.0-jammy
  node:
    docker:
      - image: cimg/node:21.7

jobs:
  accounts-unit:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn workspace accounts build && yarn workspace accounts test:unit:ci
  accounts-e2e:
    executor: playwright
    steps:
      - checkout
      - run: yarn install
      - run:
          command: yarn workspace accounts build && yarn workspace accounts test:e2e
  orders-e2e:
    executor: playwright
    steps:
      - checkout
      - run: yarn install
      - run:
          command: yarn workspace orders build && yarn workspace orders test:e2e
  shop-e2e:
    executor: playwright
    steps:
      - checkout
      - run: yarn install
      - run:
          command: yarn workspace shop build && yarn workspace shop test:e2e
  settings-e2e:
    executor: playwright
    steps:
      - checkout
      - run: yarn install
      - run:
          command: yarn workspace settings build && yarn workspace settings test:e2e
  catalog-e2e:
    executor: playwright
    steps:
      - checkout
      - run: yarn install
      - run:
          command: yarn workspace catalog build && yarn workspace catalog test:e2e

workflows:
  test:
    jobs:
      - accounts-unit
      - accounts-e2e
      - orders-e2e
      - shop-e2e
      - settings-e2e
      - catalog-e2e
