version: 2.1

orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@2.2.0

executors:
  cypress:
    docker:
      - image: 'cypress/base:16.18.1'
  playwright:
    docker:
       - image: mcr.microsoft.com/playwright:v1.32.3-jammy
  node:
    docker:
      - image: cimg/node:19.9

jobs:
  accounts-unit:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn workspace accounts build && yarn workspace accounts test:unit:ci
  accounts-e2e:
    executor: playwright
    steps:
      - checkout
      - run: yarn install
      - run:
          command: yarn workspace accounts build && yarn workspace accounts test:e2e
  orders-e2e:
    executor: playwright
    steps:
      - checkout
      - run: yarn install
      - run:
          command: yarn workspace orders build && yarn workspace orders test:e2e
      - store_artifacts:
          path: /root/project/packages/orders/packages/orders/test-results

workflows:
  test:
    jobs:
      - accounts-unit
      - accounts-e2e
      - orders-e2e
      - cypress/run:
          executor: cypress
          yarn: true
          command: yarn workspace shop build && yarn workspace shop test:e2e:ci
      - cypress/run:
          executor: cypress
          yarn: true
          command: yarn workspace catalog build && yarn workspace catalog test:e2e:ci
      - cypress/run:
          executor: cypress
          yarn: true
          command: yarn workspace settings build && yarn workspace settings test:e2e:ci
