version: 2.1

orbs:
  node: circleci/node@5.0.3
  cypress: cypress-io/cypress@2.2.0

executors:
  image:
    docker:
      - image: 'cypress/base:16.14.0'

jobs:
  accounts:
    docker:
      - image: cimg/node:16.18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn workspace accounts build && yarn workspace accounts test:unit:ci

workflows:
  test:
    jobs:
      - accounts
      - cypress/run:
          executor: image
          yarn: true
          command: yarn workspace shop build && yarn workspace shop test:e2e:ci
