version: 2.1

orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@2.2.0

executors:
  image:
    docker:
      - image: 'cypress/base:16.18.1'
  pw-focal-development:
     docker:
       - image: mcr.microsoft.com/playwright:v1.32.0-focal

jobs:
  accounts:
    docker:
      - image: cimg/node:19.9
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn workspace accounts build && yarn workspace accounts test:unit:ci
  accounts-e2e:
    executor: pw-focal-development
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Run test
          command: yarn workspace accounts build && yarn workspace accounts test:e2e

workflows:
  test:
    jobs:
      - accounts
      - accounts-e2e
      - cypress/run:
          executor: image
          yarn: true
          command: yarn workspace shop build && yarn workspace shop test:e2e:ci
      - cypress/run:
          executor: image
          yarn: true
          command: yarn workspace catalog build && yarn workspace catalog test:e2e:ci
      - cypress/run:
          executor: image
          yarn: true
          command: yarn workspace settings build && yarn workspace settings test:e2e:ci
