version: 2.1

orbs:
  node: circleci/node@4.9.0

jobs:
  test:
    docker:
      - image: cimg/node:16.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn workspace accounts build && yarn workspace accounts test:unit:ci

workflows:
  test:
    jobs:
      - test
