name: Unit-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  accounts-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.7
          cache: yarn
      - run: yarn install
      - run: yarn workspace accounts build && yarn workspace accounts test:unit:ci

  accounts-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/playwright-github-action@v3
      - run: yarn install
      - run: yarn workspace accounts build && yarn workspace accounts test:e2e

  orders-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/playwright-github-action@v3
      - run: yarn install
      - run: yarn workspace orders build && yarn workspace orders test:e2e

  shop-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/playwright-github-action@v3
      - run: yarn install
      - run: yarn workspace shop build && yarn workspace shop test:e2e

  settings-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/playwright-github-action@v3
      - run: yarn install
      - run: yarn workspace settings build && yarn workspace settings test:e2e

  catalog-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/playwright-github-action@v3
      - run: yarn install
      - run: yarn workspace catalog build && yarn workspace catalog test:e2e
