name: Unit-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shop-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm -F shop exec playwright install --with-deps
      - name: Build shop
        run: pnpm -F shop build
      - name: Run shop e2e tests
        run: pnpm -F shop test:e2e
      - uses: actions/upload-artifact@v5
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-shop
          path: playwright-report/
          retention-days: 30

  settings-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm -F settings exec playwright install --with-deps
      - name: Build settings
        run: pnpm -F settings build
      - name: Run settings e2e tests
        run: pnpm -F settings test:e2e
      - uses: actions/upload-artifact@v5
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-settings
          path: playwright-report/
          retention-days: 30

  catalog-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm -F catalog exec playwright install --with-deps
      - name: Build catalog
        run: pnpm -F catalog build
      - name: Run catalog e2e tests
        run: pnpm -F catalog test:e2e
      - uses: actions/upload-artifact@v5
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-catalog
          path: playwright-report/
          retention-days: 30
